export default {
  name: 'donateOrder',
  title: 'Payment order',
  type: 'document',
  fields: [
    {name: 'orderReference', title: 'WayForPay order reference', type: 'string', readOnly: true},
    {
      name: 'origin',
      title: 'Origin',
      type: 'string',
      options: {list: ['checkout', 'providerOnly']},
      readOnly: true,
    },
    {name: 'reconciliationStatus', title: 'Reconciliation status', type: 'string', readOnly: true},
    {name: 'amountMinor', title: 'Expected amount (kopiykas)', type: 'number', readOnly: true},
    {name: 'expectedAmount', title: 'Expected amount', type: 'number', readOnly: true},
    {name: 'currency', title: 'Currency', type: 'string', readOnly: true},
    {name: 'productName', title: 'Product name', type: 'string', readOnly: true},
    {name: 'productCount', title: 'Product count', type: 'number', readOnly: true},
    {name: 'paymentType', title: 'Payment type', type: 'string', options: {list: ['oneTime', 'monthly']}, readOnly: true},
    {name: 'initialPaymentOccurrenceId', title: 'Initial payment occurrence', type: 'string', readOnly: true},
    {name: 'isRecurringAgreed', title: 'Recurring charge consent', type: 'boolean', readOnly: true},
    {name: 'regularMode', title: 'Recurring mode', type: 'string', options: {list: ['monthly']}, readOnly: true},
    {name: 'regularAmountMinor', title: 'Recurring amount (kopiykas)', type: 'number', readOnly: true},
    {name: 'regularNextPaymentDate', title: 'Next recurring payment date', type: 'string', readOnly: true},
    {name: 'orderDate', title: 'WayForPay order date', type: 'number', readOnly: true},
    {
      name: 'donationPurpose',
      title: 'Donation purpose',
      type: 'string',
      options: {list: ['foundation', 'collection', 'tail-one-time', 'tail-guardianship']},
      readOnly: true,
    },
    {name: 'donationTargetId', title: 'Donation target ID', type: 'string', readOnly: true},
    {name: 'donationTargetName', title: 'Donation target', type: 'string', readOnly: true},
    {name: 'returnPath', title: 'Return path', type: 'string', readOnly: true},
    {name: 'comment', title: 'Comment', type: 'string', readOnly: true},
    {name: 'donorFullName', title: 'Donor full name (not anonymous)', type: 'string', readOnly: true},
    {name: 'isAnonymous', title: 'Anonymous donation', type: 'boolean', readOnly: true},
    {name: 'isAgreed', title: 'Agreed to offer', type: 'boolean', readOnly: true},
    {name: 'wantNotifications', title: 'Consent to notifications', type: 'boolean', readOnly: true},
    {
      name: 'paymentStatus',
      title: 'Payment status',
      type: 'string',
      options: {list: ['created', 'pending', 'approved', 'failed', 'reversed', 'unknown']},
      readOnly: true,
    },
    {name: 'providerTransactionStatus', title: 'Provider status', type: 'string', readOnly: true},
    {name: 'providerReasonCode', title: 'Provider reason code', type: 'string', readOnly: true},
    {name: 'providerReason', title: 'Provider reason', type: 'string', readOnly: true},
    {name: 'payerEmail', title: 'Payer email (with consent)', type: 'string', readOnly: true},
    {name: 'payerPhone', title: 'Payer phone (with consent)', type: 'string', readOnly: true},
    {name: 'lastCallbackEventId', title: 'Last callback event ID', type: 'string', readOnly: true},
    {name: 'callbackDeliveryCount', title: 'Verified callback deliveries', type: 'number', readOnly: true},
    {name: 'lastProviderProcessingDate', title: 'Provider processing timestamp', type: 'number', readOnly: true},
    {name: 'lastProviderProcessingAt', title: 'Provider processing time', type: 'datetime', readOnly: true},
    {name: 'lastCallbackAt', title: 'Last callback received at', type: 'datetime', readOnly: true},
    {name: 'lastReconciledAt', title: 'Last reconciled at', type: 'datetime', readOnly: true},
    {name: 'donationEmailEnabled', title: 'Donation email enabled', type: 'boolean', readOnly: true},
    {
      name: 'donationEmailStatus',
      title: 'Donation email status',
      type: 'string',
      options: {list: ['pending', 'sent']},
      readOnly: true,
    },
    {name: 'donationEmailAttemptCount', title: 'Donation email attempts', type: 'number', readOnly: true},
    {name: 'donationEmailLastAttemptAt', title: 'Donation email last attempt', type: 'datetime', readOnly: true},
    {name: 'donationEmailSentAt', title: 'Donation email sent at', type: 'datetime', readOnly: true},
    {name: 'donationEmailProviderId', title: 'Donation email provider ID', type: 'string', readOnly: true},
    {name: 'donationEmailLastErrorCode', title: 'Donation email last error', type: 'string', readOnly: true},
    {name: 'createdAt', title: 'Created at', type: 'datetime', readOnly: true},
  ],
}
