export default {
  name: 'paymentOccurrence',
  title: 'Payment occurrence',
  type: 'document',
  fields: [
    {name: 'occurrenceId', title: 'Occurrence ID', type: 'string', readOnly: true},
    {name: 'orderReference', title: 'Order reference', type: 'string', readOnly: true},
    {name: 'authCode', title: 'Provider authorization code', type: 'string', readOnly: true},
    {name: 'amountMinor', title: 'Amount (kopiykas)', type: 'number', readOnly: true},
    {name: 'currency', title: 'Currency', type: 'string', readOnly: true},
    {
      name: 'paymentStatus',
      title: 'Payment status',
      type: 'string',
      options: {list: ['created', 'pending', 'approved', 'failed', 'reversed', 'unknown']},
      readOnly: true,
    },
    {name: 'providerTransactionStatus', title: 'Provider status', type: 'string', readOnly: true},
    {name: 'providerReasonCode', title: 'Provider reason code', type: 'string', readOnly: true},
    {name: 'providerReason', title: 'Provider reason', type: 'string', readOnly: true},
    {name: 'lastProviderProcessingDate', title: 'Provider processing timestamp', type: 'number', readOnly: true},
    {name: 'lastProviderProcessingAt', title: 'Provider processing time', type: 'datetime', readOnly: true},
    {name: 'donationEmailStatus', title: 'Donation email status', type: 'string', options: {list: ['pending', 'sent']}, readOnly: true},
    {name: 'donationEmailAttemptCount', title: 'Donation email attempts', type: 'number', readOnly: true},
    {name: 'donationEmailLastAttemptAt', title: 'Donation email last attempt', type: 'datetime', readOnly: true},
    {name: 'donationEmailSentAt', title: 'Donation email sent at', type: 'datetime', readOnly: true},
    {name: 'donationEmailProviderId', title: 'Donation email provider ID', type: 'string', readOnly: true},
    {name: 'donationEmailLastErrorCode', title: 'Donation email last error', type: 'string', readOnly: true},
    {name: 'createdAt', title: 'Created at', type: 'datetime', readOnly: true},
    {name: 'updatedAt', title: 'Updated at', type: 'datetime', readOnly: true},
  ],
}
