export default {
  name: 'wayforpayCallback',
  title: 'WayForPay callback',
  type: 'document',
  fields: [
    {name: 'source', title: 'Source', type: 'string', options: {list: ['callback', 'reconciliation']}, readOnly: true},
    {name: 'orderReference', title: 'Order reference', type: 'string', readOnly: true},
    {name: 'occurrenceId', title: 'Payment occurrence', type: 'string', readOnly: true},
    {name: 'receivedAt', title: 'Received at', type: 'datetime', readOnly: true},
    {name: 'signatureValid', title: 'Signature valid', type: 'boolean', readOnly: true},
    {name: 'merchantAccount', title: 'Merchant account', type: 'string', readOnly: true},
    {name: 'merchantSignature', title: 'Merchant signature', type: 'string', readOnly: true},
    {name: 'amount', title: 'Amount', type: 'string', readOnly: true},
    {name: 'amountMinor', title: 'Amount (kopiykas)', type: 'number', readOnly: true},
    {name: 'currency', title: 'Currency', type: 'string', readOnly: true},
    {name: 'authCode', title: 'Auth code', type: 'string', readOnly: true},
    {name: 'cardPan', title: 'Masked card PAN', type: 'string', readOnly: true},
    {name: 'cardType', title: 'Card type', type: 'string', readOnly: true},
    {name: 'issuerBankCountry', title: 'Issuer country', type: 'string', readOnly: true},
    {name: 'issuerBankName', title: 'Issuer bank', type: 'string', readOnly: true},
    {name: 'transactionStatus', title: 'Provider status', type: 'string', readOnly: true},
    {name: 'normalizedStatus', title: 'Normalized status', type: 'string', readOnly: true},
    {name: 'reason', title: 'Reason', type: 'string', readOnly: true},
    {name: 'reasonCode', title: 'Reason code', type: 'string', readOnly: true},
    {name: 'fee', title: 'Fee', type: 'string', readOnly: true},
    {name: 'paymentSystem', title: 'Payment system', type: 'string', readOnly: true},
    {name: 'createdDate', title: 'Provider creation timestamp', type: 'number', readOnly: true},
    {name: 'processingDate', title: 'Provider processing timestamp', type: 'number', readOnly: true},
    {name: 'processingDateIso', title: 'Provider processing time', type: 'datetime', readOnly: true},
    {name: 'payerEmail', title: 'Payer email (with consent)', type: 'string', readOnly: true},
    {name: 'payerPhone', title: 'Payer phone (with consent)', type: 'string', readOnly: true},
    {name: 'callbackPayloadEncrypted', title: 'Encrypted callback payload', type: 'encryptedValue', readOnly: true},
    {name: 'recTokenEncrypted', title: 'Encrypted recurring token', type: 'encryptedValue', readOnly: true},
    {name: 'repayUrlEncrypted', title: 'Encrypted repay URL', type: 'encryptedValue', readOnly: true},
  ],
}
